export const FETCH_DATA_PRODUCTLIST = 'FETCH_DATA_PRODUCTLIST'
export const FETCH_DATA_PRODUCTLIST_PENDING = 'FETCH_DATA_PRODUCTLIST_PENDING'
export const FETCH_DATA_PRODUCTLIST_FULFILLED = 'FETCH_DATA_PRODUCTLIST_FULFILLED'
export const FETCH_DATA_PRODUCTLIST_REJECTED = 'FETCH_DATA_PRODUCTLIST_REJECTED'


export const FETCH_DATA_PRODUCTDETAIL = 'FETCH_DATA_PRODUCTDETAIL'
export const FETCH_DATA_PRODUCTDETAIL_PENDING = 'FETCH_DATA_PRODUCTDETAIL_PENDING'
export const FETCH_DATA_PRODUCTDETAIL_FULFILLED = 'FETCH_DATA_PRODUCTDETAIL_FULFILLED'
export const FETCH_DATA_PRODUCTDETAIL_REJECTED = 'FETCH_DATA_PRODUCTDETAIL_REJECTED'
export const FLUSH_PRODUCT_DETAILS = 'FLUSH_PRODUCT_DETAILS'


export const ADD_TO_CART = 'ADD_TO_CART'
export const INCREMENT_ITEM = 'INCREMENT_ITEM'
export const DECREMENT_ITEM = 'DECREMENT_ITEM'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const ITEM_ADDED_LIGHTBOX = 'ITEM_ADDED_LIGHTBOX'


export const FETCH_DATA_BUY_PRODUCTS = 'FETCH_DATA_BUY_PRODUCTS'
export const FETCH_DATA_BUY_PRODUCTS_PENDING = 'FETCH_DATA_BUY_PRODUCTS_PENDING'
export const FETCH_DATA_BUY_PRODUCTS_FULFILLED = 'FETCH_DATA_BUY_PRODUCTS_FULFILLED'
export const FETCH_DATA_BUY_PRODUCTS_REJECTED = 'FETCH_DATA_BUY_PRODUCTS_REJECTED'